### ISSUE TITLE
Adding possibility for `Show more` option on payload message

### ISSUE THREAD

**Issue by MartyCatawiki** [crazymanish/fastlane-plugin-slack_bot#3]
It would be really nice if we can have a `Show more` option per payload item.
<img width="415" alt="Screenshot 2021-04-20 at 15 13 22" src="https://user-images.githubusercontent.com/12713254/115516969-f1bdd780-a286-11eb-9296-c45b0d768ec9.png">

**Comment by crazymanish** [comment]
Hi @MartyCatawiki 

Slack by default supports the **show more** option in the message. 
please note **payload** does not support show more option.


Example: **payload** does not showing "show more" option
<img width="1420" alt="Screenshot 2021-04-21 at 13 32 35" src="https://user-images.githubusercontent.com/5364500/115548055-4d985880-a2a7-11eb-9038-3ddb50ad016d.png">

.
.
Example: **message** supports "show more" option
<img width="1750" alt="Screenshot 2021-04-21 at 13 34 33" src="https://user-images.githubusercontent.com/5364500/115548137-67d23680-a2a7-11eb-82f1-0945b6c598bd.png">


We don't have to do anything to support the "Show more" option, so closing this issue. Please feel to re-open in case of any issue 😊

**Comment by MartyCatawiki** [comment]
Thanks for explaining @crazymanish 👍🏼 

Let's hope that they support `show more` per payLoad in the future, because otherwise with the workaround it will hide too much information.

Enjoy your Holiday and let's have a chat after your Holiday. 💪🏼
