### ISSUE TITLE
Error with file upload/slack API

### ISSUE THREAD

**Issue by levidps** [crazymanish/fastlane-plugin-slack_bot#5]
Upon trying to upload an `.apk` file I came across and error between the plugin and slacks API. In the plugin file it's passing in a file name minus the file type suffix however when reviewing the [slack API](https://api.slack.com/methods/files.upload#arg_filename) the suffix is required when supplying a file name. The result is when uploading an apk you get the following API call:

```
file_path: "./dev/release/output/flavour/my-apk.apk
```

```
# file_upload_to_slack.rb
# Slack upload params - currently missing suffix from filename

filename: "my-apk",
filetype: "apk",
```

This results in slack trying to guess the file type and for apks they fall back to `.zip` - which isn't correct since APK is a supported file type. This can be worked around currently by ensuring we supply a `file_name: ...#{type}` however the plugin should be smart enough to actually append the suffix to file name (or not strip it in the first place).

```
# Expected payload

filename: "my-apk.apk",
filetype: "apk",
```

**Comment by crazymanish** [comment]
Hi @levidps 

This looks like a bug to me indeed, thank you for reporting! 😇
are you blocked at the moment, or did you manage to unblock yourself using a workaround?

I will open PR soon and let you know to test once that PR before merging into master. thanks again!

**Comment by levidps** [comment]
@crazymanish I was able to get a workaround by specifying the `file_type` and `file_name` in the `file_upload_to_slack()` method. It works fine but just required explicitly setting file name/type correctly.

**Comment by crazymanish** [comment]
As we have a working workaround. closing it.
