### ISSUE TITLE
Custom username and icon don't work

### ISSUE THREAD

**Issue by absoftware** [crazymanish/fastlane-plugin-slack_bot#8]
Hello there! Thank you for releasing this wonderful plugin. It's really useful. Just reporting some issue related to custom username and icon url. I don't get customised username and icon when using:

```
release_thread = post_to_slack(
  as_user: false,
  api_token: slack_api_token,
  channel: slack_channel,
  message: "Test for custom icon and bot name",
  icon_url: "https://fastlane.tools/assets/img/fastlane_icon.png",
  username: "Release Bot",
)
```

![screenshot](https://user-images.githubusercontent.com/41308513/209987352-c465a1ce-9664-42ff-a46f-a7723eee00dd.png)

It's probably because of the line

```
payload[:as_user] = options[:as_user] if options[:as_user] # default is false
```

I don't know Ruby very well, but I suspect it doesn't set `as_user` explicitly as `false` in payload, but only when it's `true`. According to Slack's documentation it must be set explicitly to make it working:

> Legacy authorship 
> Classic Slack apps using the umbrella bot scope can't request additional scopes to adjust message authorship.
>
> For classic Slack apps, the best way to control the authorship of a message is to be explicit with the as_user parameter.
>
> If you don't use the as_user parameter, chat.postMessage will guess the most appropriate as_user interpretation based on the kind of token you're using.
>
> If as_user is not provided at all, then the value is inferred, based on the scopes granted to the caller: If the caller could post with as_user passed as false, then that is how the method behaves; otherwise, the method behaves as if as_user were passed as true.

https://api.slack.com/methods/chat.postMessage#legacy_authorship 

It would be nice to have it working for all actions (message, message in thread, upload, upload in thread).

**Comment by crazymanish** [comment]
@absoftware 
Question: did you try the below? because it works/working for me like below with a custom name and URL

```swift
post_to_slack(
  api_token: slack_api_token,
  channel: slack_channel,
  message: "Test for custom icon and bot name",
  icon_url: "https://fastlane.tools/assets/img/fastlane_icon.png",
  username: "Release Bot",
)

**Comment by crazymanish** [comment]
it is working for me in the thread as well 😇 adding example:

  before_all do
    # Used by Fastlane's slack (post_to_slack action)
    ENV["FL_SLACK_USERNAME"] = "Release Bot"
    ENV["FL_SLACK_ICON_URL"] = "https://fastlane.tools/assets/img/fastlane_icon.png"
    ENV["SLACK_API_TOKEN"] = "XXXX-XXXXXXXXXXX-XXXXXXX"
  end

```ruby
result = post_to_slack(
    channel: slack_channel,
    message: "Test for custom icon and bot name"
)

# Important: Save this slack-thread timestamp for further slack messages
thread_ts = result[:json]["ts"]

....
....
....

# Sending a testing message in the above thread
post_to_slack(
    channel: slack_channel,
    message: "Sending a slack message in the thread with custom icon and bot name",
    thread_ts: thread_ts # Using slack-message timestamp to post this message inside the thread
)

**Comment by absoftware** [comment]
@crazymanish Thank you for checking this. Apparently it depends on settings in our Slack's workspace for this app or bot. I tested different options at https://api.slack.com/methods/chat.postMessage/test and no expected results as well. I will verify this together with admin next week.
